# Generated by Django 5.2.17 on 2026-08-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_portfolioimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='company_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='professional',
            name='completed_projects',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='professional',
            name='max_budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='min_budget',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professional',
            name='provider_type',
            field=models.CharField(choices=[('individual', 'Individual Professional'), ('contractor', 'Contractor')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='professional',
            name='team_size',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
