# Generated by Django 5.2.17 on 2026-08-20 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_professional_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professional',
            name='max_budget',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='min_budget',
        ),
        migrations.CreateModel(
            name='ConstructionProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plot_area', models.PositiveIntegerField()),
                ('built_up_area', models.PositiveIntegerField()),
                ('floors', models.PositiveIntegerField(default=1)),
                ('location', models.CharField(max_length=150)),
                ('construction_quality', models.CharField(choices=[('basic', 'Basic'), ('standard', 'Standard'), ('premium', 'Premium'), ('luxury', 'Luxury')], max_length=20)),
                ('actual_cost', models.PositiveIntegerField()),
                ('completion_year', models.PositiveIntegerField()),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_projects', to='professionals.professional')),
            ],
        ),
    ]
