# Generated by Django 5.2.17 on 2026-08-21 04:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0004_remove_professional_max_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionproject',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioimage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='professionals.constructionproject'),
        ),
    ]
