# Generated by Django 5.2.17 on 2026-08-21 09:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0005_constructionproject_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionproject',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='constructionproject',
            name='title',
            field=models.CharField(default='Previous Construction Project', max_length=200),
        ),
    ]
