# Generated by Django 5.2.17 on 2026-08-21 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0006_constructionproject_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='rate',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
